/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as DotwellKnownMcpRouteImport } from './routes/[.]well-known/mcp'
import { Route as McpSchemaRouteImport } from './routes/mcp.schema'
import { Route as ApiV1CatalogRouteImport } from './routes/api/v1/catalog'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1SettlementsRouteImport } from './routes/api/v1/settlements'
import { Route as ApiV1TreasuryRouteImport } from './routes/api/v1/treasury'
import { Route as ApiV1ProxyQuoteRouteImport } from './routes/api/v1/proxy/quote'
import { Route as ApiV1ProxyScrapeRouteImport } from './routes/api/v1/proxy/scrape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpRoute = DotwellKnownMcpRouteImport.update({
  id: '/.well-known/mcp',
  path: '/.well-known/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSchemaRoute = McpSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => McpRoute,
} as any)
const ApiV1CatalogRoute = ApiV1CatalogRouteImport.update({
  id: '/api/v1/catalog',
  path: '/api/v1/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettlementsRoute = ApiV1SettlementsRouteImport.update({
  id: '/api/v1/settlements',
  path: '/api/v1/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TreasuryRoute = ApiV1TreasuryRouteImport.update({
  id: '/api/v1/treasury',
  path: '/api/v1/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProxyQuoteRoute = ApiV1ProxyQuoteRouteImport.update({
  id: '/api/v1/proxy/quote',
  path: '/api/v1/proxy/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProxyScrapeRoute = ApiV1ProxyScrapeRouteImport.update({
  id: '/api/v1/proxy/scrape',
  path: '/api/v1/proxy/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/deploy': typeof DeployRoute
  '/integrate': typeof IntegrateRoute
  '/ledger': typeof LedgerRoute
  '/mcp': typeof McpRouteWithChildren
  '/treasury': typeof TreasuryRoute
  '/.well-known/mcp': typeof DotwellKnownMcpRoute
  '/mcp/schema': typeof McpSchemaRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/settlements': typeof ApiV1SettlementsRoute
  '/api/v1/treasury': typeof ApiV1TreasuryRoute
  '/api/v1/proxy/quote': typeof ApiV1ProxyQuoteRoute
  '/api/v1/proxy/scrape': typeof ApiV1ProxyScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/deploy': typeof DeployRoute
  '/integrate': typeof IntegrateRoute
  '/ledger': typeof LedgerRoute
  '/mcp': typeof McpRouteWithChildren
  '/treasury': typeof TreasuryRoute
  '/.well-known/mcp': typeof DotwellKnownMcpRoute
  '/mcp/schema': typeof McpSchemaRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/settlements': typeof ApiV1SettlementsRoute
  '/api/v1/treasury': typeof ApiV1TreasuryRoute
  '/api/v1/proxy/quote': typeof ApiV1ProxyQuoteRoute
  '/api/v1/proxy/scrape': typeof ApiV1ProxyScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/deploy': typeof DeployRoute
  '/integrate': typeof IntegrateRoute
  '/ledger': typeof LedgerRoute
  '/mcp': typeof McpRouteWithChildren
  '/treasury': typeof TreasuryRoute
  '/.well-known/mcp': typeof DotwellKnownMcpRoute
  '/mcp/schema': typeof McpSchemaRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/settlements': typeof ApiV1SettlementsRoute
  '/api/v1/treasury': typeof ApiV1TreasuryRoute
  '/api/v1/proxy/quote': typeof ApiV1ProxyQuoteRoute
  '/api/v1/proxy/scrape': typeof ApiV1ProxyScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/console'
    | '/deploy'
    | '/integrate'
    | '/ledger'
    | '/mcp'
    | '/treasury'
    | '/.well-known/mcp'
    | '/mcp/schema'
    | '/api/v1/catalog'
    | '/api/v1/health'
    | '/api/v1/settlements'
    | '/api/v1/treasury'
    | '/api/v1/proxy/quote'
    | '/api/v1/proxy/scrape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/console'
    | '/deploy'
    | '/integrate'
    | '/ledger'
    | '/mcp'
    | '/treasury'
    | '/.well-known/mcp'
    | '/mcp/schema'
    | '/api/v1/catalog'
    | '/api/v1/health'
    | '/api/v1/settlements'
    | '/api/v1/treasury'
    | '/api/v1/proxy/quote'
    | '/api/v1/proxy/scrape'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/console'
    | '/deploy'
    | '/integrate'
    | '/ledger'
    | '/mcp'
    | '/treasury'
    | '/.well-known/mcp'
    | '/mcp/schema'
    | '/api/v1/catalog'
    | '/api/v1/health'
    | '/api/v1/settlements'
    | '/api/v1/treasury'
    | '/api/v1/proxy/quote'
    | '/api/v1/proxy/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ConsoleRoute: typeof ConsoleRoute
  DeployRoute: typeof DeployRoute
  IntegrateRoute: typeof IntegrateRoute
  LedgerRoute: typeof LedgerRoute
  McpRoute: typeof McpRouteWithChildren
  TreasuryRoute: typeof TreasuryRoute
  DotwellKnownMcpRoute: typeof DotwellKnownMcpRoute
  ApiV1CatalogRoute: typeof ApiV1CatalogRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1SettlementsRoute: typeof ApiV1SettlementsRoute
  ApiV1TreasuryRoute: typeof ApiV1TreasuryRoute
  ApiV1ProxyQuoteRoute: typeof ApiV1ProxyQuoteRoute
  ApiV1ProxyScrapeRoute: typeof ApiV1ProxyScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp': {
      id: '/.well-known/mcp'
      path: '/.well-known/mcp'
      fullPath: '/.well-known/mcp'
      preLoaderRoute: typeof DotwellKnownMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/schema': {
      id: '/mcp/schema'
      path: '/schema'
      fullPath: '/mcp/schema'
      preLoaderRoute: typeof McpSchemaRouteImport
      parentRoute: typeof McpRoute
    }
    '/api/v1/catalog': {
      id: '/api/v1/catalog'
      path: '/api/v1/catalog'
      fullPath: '/api/v1/catalog'
      preLoaderRoute: typeof ApiV1CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settlements': {
      id: '/api/v1/settlements'
      path: '/api/v1/settlements'
      fullPath: '/api/v1/settlements'
      preLoaderRoute: typeof ApiV1SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/treasury': {
      id: '/api/v1/treasury'
      path: '/api/v1/treasury'
      fullPath: '/api/v1/treasury'
      preLoaderRoute: typeof ApiV1TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/proxy/quote': {
      id: '/api/v1/proxy/quote'
      path: '/api/v1/proxy/quote'
      fullPath: '/api/v1/proxy/quote'
      preLoaderRoute: typeof ApiV1ProxyQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/proxy/scrape': {
      id: '/api/v1/proxy/scrape'
      path: '/api/v1/proxy/scrape'
      fullPath: '/api/v1/proxy/scrape'
      preLoaderRoute: typeof ApiV1ProxyScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface McpRouteChildren {
  McpSchemaRoute: typeof McpSchemaRoute
}

const McpRouteChildren: McpRouteChildren = {
  McpSchemaRoute: McpSchemaRoute,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ConsoleRoute: ConsoleRoute,
  DeployRoute: DeployRoute,
  IntegrateRoute: IntegrateRoute,
  LedgerRoute: LedgerRoute,
  McpRoute: McpRouteWithChildren,
  TreasuryRoute: TreasuryRoute,
  DotwellKnownMcpRoute: DotwellKnownMcpRoute,
  ApiV1CatalogRoute: ApiV1CatalogRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1SettlementsRoute: ApiV1SettlementsRoute,
  ApiV1TreasuryRoute: ApiV1TreasuryRoute,
  ApiV1ProxyQuoteRoute: ApiV1ProxyQuoteRoute,
  ApiV1ProxyScrapeRoute: ApiV1ProxyScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
